nav:
  logo: #image
  display_title: true
  fixed: false # fixed navigation bar

menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  分类: /categories/ || fas fa-folder-open
  标签: /tags/ || fas fa-tags
  清单||fas fa-list:
    音乐: /music/ || fas fa-music
    电影: /movies/ || fas fa-video
    图库: /gallery/ || fas fa-images
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# 代碼相關
highlight_theme: ocean # 高亮主题： darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # 支持代码复制
highlight_lang: true # show the code language
highlight_shrink: false # 代碼框不展開，需點擊 '>' 打開。可在front-matter添加highlight_shrink來獨立配置。true、false、none
highlight_height_limit: false # 单位：px
code_word_wrap: false # 代碼換行,如果你是使用 highlight 渲染，需要找到你站點的 Hexo 配置文件_config.yml，將line_number改成false

# 搜索
# search:
#   path: search.xml
#   field: post
#   content: true
#   template: ./search.xml
# 本地搜索
local_search:
  enable: true  # 是否開啟本地搜索
  # Preload the search data when the page loads.預加載，開啟後，進入網頁後會自動加載搜索文件。關閉時，只有點擊搜索按鈕後，才會加載搜索文件
  preload: false
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  CDN:

# 分享显示的内容  https://github.com/overtrue/share.js/
sharejs:
  enable: true
  sites: wechat,weibo,qq

# 音乐aplayer
aplayer:
  meting: true
  asset_inject: false
aplayerInject:
  enable: true
  per_page: true
inject:
  head:
  # bottom:
  - <div class="aplayer no-destroy" data-id="5199155506" data-server="netease" data-type="playlist" data-fixed="true" data-autoplay="false" data-preload="false"> </div>
# Pjax
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
# 全局播放背景音乐（使用 Pajx 实现）
# 即实现页面跳转刷新后音乐不间断播放
pjax:
  enable: true

# 数学公式
# mathjax:
#   enable: true
#   # true 表示每一頁都加載mathjax.js
#   # false 需要時加載，須在使用的Markdown Front-matter 加上 mathjax: true
#   per_page: false

katex:
  enable: true
  # true 表示每一頁都加載katex.js
  # false 需要時加載，須在使用的Markdown Front-matter 加上 katex: true
  per_page: false
  hide_scrollbar: true
